name: Build and upload python package to PyPI

on:
  workflow_dispatch

jobs:
  release-pypi:
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Build package and upload from docker (Linux)
      if: runner.os == 'Linux'
      run: |
        docker run --rm -v "${PWD}:/opt/FastTokenizer" ubuntu:16.04 \
          "cd /opt/FastTokenizer; /bin/bash /opt/FastTokenizer/scripts/release-pypi.bash"
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

    - name: Build package and upload (macOS)
      if: runner.os == 'macOS'
      run: bash scripts/release-pypi.bash
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
